version: "3"
services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - .dbSql:/var/lib/mysql
    restart: always
    # env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp
      MYSQL_USER: nonroot
      MYSQL_PASSWORD: nonroot
    networks:
      - wpNetwork
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    # env_file: .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nonroot
      MYSQL_PASSWORD: nonroot
    networks:
      - wpNetwork
  # WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    volumes: [ "./html:/var/www/html" ]
    # env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: nonroot
      WORDPRESS_DB_PASSWORD: nonroot
    networks:
      - wpNetwork
networks:
  wpNetwork:
volumes:
  db_data:
  wp_data:
